/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package turtlevehiclecontroller;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;

/**
 *
 * @author clatulip
 */
public class TurtleVehicleController extends javax.swing.JFrame {
    private TurtleVehicleModel myModel;
    /**
     * Creates new form TurtleVehicleController
     */
    public TurtleVehicleController(TurtleVehicleModel model) {
        initComponents();
        this.myModel = model;
        this.updateCoords();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDownButton = new javax.swing.JButton();
        jUpButton = new javax.swing.JButton();
        jTitleLabel = new javax.swing.JLabel();
        jResetButton = new javax.swing.JButton();
        jLeftButton = new javax.swing.JButton();
        jRightButton = new javax.swing.JButton();
        jXLabel = new javax.swing.JLabel();
        jXCoordLabel = new javax.swing.JLabel();
        jYLabel = new javax.swing.JLabel();
        jYCoordLabel = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        Slider = new javax.swing.JLabel();
        Stunts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDownButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jDownButton.setText("Down");
        jDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownButtonActionPerformed(evt);
            }
        });

        jUpButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jUpButton.setText("Up");
        jUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpButtonActionPerformed(evt);
            }
        });

        jTitleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTitleLabel.setText("TurtlePlane Controller");

        jResetButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        jLeftButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLeftButton.setText("Left");
        jLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLeftButtonActionPerformed(evt);
            }
        });

        jRightButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jRightButton.setText("Right");
        jRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRightButtonActionPerformed(evt);
            }
        });

        jXLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jXLabel.setText("X:");

        jYLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jYLabel.setText("Y:");

        jYCoordLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);

        Slider.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        Slider.setText("Movement Speed");

        Stunts.setText("Stunt");
        Stunts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuntsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLeftButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRightButton)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDownButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Stunts)
                        .addGap(37, 37, 37)
                        .addComponent(jXLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXCoordLabel)
                        .addGap(46, 46, 46)
                        .addComponent(jYLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jYCoordLabel)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jResetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel)
                    .addComponent(jXCoordLabel)
                    .addComponent(jYLabel)
                    .addComponent(jYCoordLabel)
                    .addComponent(Stunts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jUpButton)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLeftButton)
                    .addComponent(jRightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDownButton)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jResetButton)
                        .addComponent(Slider))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDownButtonActionPerformed
        // TODO add your handling code here:
        myModel.setHeading(180);
        myModel.forward(jSlider1.getValue());
        this.updateCoords();
    }//GEN-LAST:event_jDownButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        // TODO add your handling code here:
        myModel.setHeading(0);
        myModel.setPos(myModel.getWorldWidth()/2, myModel.getWorldHeight()/2);
        this.updateCoords();
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpButtonActionPerformed
        // TODO add your handling code here:
        myModel.setHeading(0);
        myModel.forward(jSlider1.getValue());
        this.updateCoords();
    }//GEN-LAST:event_jUpButtonActionPerformed

    private void jRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRightButtonActionPerformed
        // TODO add your handling code here:
        myModel.setHeading(90);
        myModel.forward(jSlider1.getValue());
        this.updateCoords();
    }//GEN-LAST:event_jRightButtonActionPerformed

    private void jLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLeftButtonActionPerformed
        // TODO add your handling code here:
        myModel.setHeading(270);
        myModel.forward(jSlider1.getValue());
        this.updateCoords();
    }//GEN-LAST:event_jLeftButtonActionPerformed

    private void StuntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuntsActionPerformed
        // TODO add your handling code here:
        myModel.drawSquare();
        this.updateCoords();
    }//GEN-LAST:event_StuntsActionPerformed


    private void updateCoords() {
        jXCoordLabel.setText(Integer.toString(myModel.getTurtleX()));
        jYCoordLabel.setText(Integer.toString(myModel.getTurtleY()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Slider;
    private javax.swing.JButton Stunts;
    private javax.swing.JButton jDownButton;
    private javax.swing.JButton jLeftButton;
    private javax.swing.JButton jResetButton;
    private javax.swing.JButton jRightButton;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JButton jUpButton;
    private javax.swing.JLabel jXCoordLabel;
    private javax.swing.JLabel jXLabel;
    private javax.swing.JLabel jYCoordLabel;
    private javax.swing.JLabel jYLabel;
    // End of variables declaration//GEN-END:variables
}
